# Generated by Django 6.0.5 on 2026-05-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الخطة')),
                ('duration_months', models.IntegerField(verbose_name='المدة (أشهر)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأخير')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='الهاتف')),
                ('subscription_id', models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الاشتراك')),
                ('color_status', models.CharField(choices=[('green', 'أخضر — سداد منتظم'), ('yellow', 'أصفر — تأخير بسيط'), ('red', 'أحمر — تأخير كبير')], default='green', max_length=10, verbose_name='التصنيف اللوني')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='خط العرض')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='خط الطول')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('subscription_start', models.DateField(auto_now_add=True, verbose_name='بداية الاشتراك')),
                ('subscription_end', models.DateField(blank=True, null=True, verbose_name='نهاية الاشتراك')),
                ('is_paused', models.BooleanField(default=False, verbose_name='إيقاف مؤقت')),
                ('excuse', models.TextField(blank=True, verbose_name='عذر التأخر عن السداد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_profile', to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='zones.zone', verbose_name='المنطقة')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribers.subscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
            },
        ),
    ]
