# Generated by Django 6.0.5 on 2026-05-31 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_subscription_ids(apps, schema_editor):
    Subscriber = apps.get_model('subscribers', 'Subscriber')
    seen = set()

    for subscriber in Subscriber.objects.order_by('id'):
        current = (subscriber.subscription_id or '').strip()
        needs_new_value = not current or current in seen or len(current) > 20

        if needs_new_value:
            base = f'SUB-{subscriber.pk:06d}'
            candidate = base
            suffix = 1
            while candidate in seen or Subscriber.objects.filter(subscription_id=candidate).exclude(pk=subscriber.pk).exists():
                suffix += 1
                candidate = f'{base[:15]}-{suffix}'
            Subscriber.objects.filter(pk=subscriber.pk).update(subscription_id=candidate)
            seen.add(candidate)
        else:
            seen.add(current)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Subscription plan', 'verbose_name_plural': 'Subscription plans'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='archive_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='pause_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='paused_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(dedupe_subscription_ids, noop_reverse),
        migrations.AlterField(
            model_name='subscriber',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='color_status',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='excuse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribers.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscription_id',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscription_start',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='zones.zone'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration_months',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
