# Generated by Django 6.0.5 on 2026-06-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_alter_subscriber_options_and_more'),
        ('zones', '0002_alter_route_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='pause_reason',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='zones.route'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='bins_count',
            field=models.IntegerField(default=1),
        ),
    ]
