# Generated by Django 6.0.5 on 2026-06-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_remove_subscriber_pause_reason_subscriber_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribers.subscriptionplan', verbose_name='Plan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_logs', to='subscribers.subscriber', verbose_name='Subscriber')),
            ],
            options={
                'verbose_name': 'Subscription Log',
                'verbose_name_plural': 'Subscription Logs',
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
