# Generated by Django 6.0.5 on 2026-06-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_plan'),
        ('subscribers', '0004_subscriptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_logs', to='finance.payment', verbose_name='Payment'),
        ),
    ]
