# Generated by Django 6.0.5 on 2026-05-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('category', models.CharField(choices=[('fuel', 'وقود'), ('maintenance', 'صيانة'), ('salary', 'رواتب'), ('other', 'أخرى')], default='other', max_length=15, verbose_name='الفئة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('active', 'قيد السداد'), ('paid', 'مسددة')], default='active', max_length=10, verbose_name='الحالة')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السُلف',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('pending', 'بانتظار التوريد'), ('deposited', 'تم التوريد')], default='confirmed', max_length=15, verbose_name='الحالة')),
                ('receipt_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الإيصال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='المندوب')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscribers.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'تحصيل',
                'verbose_name_plural': 'التحصيلات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='السبب')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المبلغ')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'جزاء',
                'verbose_name_plural': 'الجزاءات',
            },
        ),
    ]
