# Generated by Django 6.0.5 on 2026-05-31 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def dedupe_receipt_numbers(apps, schema_editor):
    Payment = apps.get_model('finance', 'Payment')
    seen = set()

    for payment in Payment.objects.order_by('id'):
        current = (payment.receipt_number or '').strip()
        needs_new_value = not current or current in seen or len(current) > 20

        if needs_new_value:
            base = f'REC-{payment.pk:06d}'
            candidate = base
            suffix = 1
            while candidate in seen or Payment.objects.filter(receipt_number=candidate).exclude(pk=payment.pk).exists():
                suffix += 1
                candidate = f'{base[:15]}-{suffix}'
            Payment.objects.filter(pk=payment.pk).update(receipt_number=candidate)
            seen.add(candidate)
        else:
            seen.add(current)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advance',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Advance', 'verbose_name_plural': 'Advances'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Penalty', 'verbose_name_plural': 'Penalties'},
        ),
        migrations.AlterField(
            model_name='advance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='advance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advance',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advance',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paid', 'Paid')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('salary', 'Salary'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=15),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RunPython(dedupe_receipt_numbers, noop_reverse),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending deposit'), ('deposited', 'Deposited')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscribers.subscriber'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='StaffReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff reward',
                'verbose_name_plural': 'Staff rewards',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
