# Generated by Django 6.0.5 on 2026-06-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agentprofile_options_and_more'),
        ('finance', '0002_alter_advance_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='accounts.agentprofile'),
        ),
    ]
