# Generated by Django 6.0.5 on 2026-06-05 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_agentprofile_first_name_and_more'),
        ('finance', '0003_alter_payment_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='accounts.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='accounts.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='staffreward',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_rewards', to='accounts.employeeprofile'),
        ),
    ]
