# Generated by Django 6.0.5 on 2026-06-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_advance_employee_alter_penalty_employee_and_more'),
        ('subscribers', '0004_subscriptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscribers.subscriptionplan', verbose_name='Subscription Plan'),
        ),
    ]
