# Generated by Django 6.0.5 on 2026-06-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_agentprofile_first_name_and_more'),
        ('finance', '0005_payment_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15, verbose_name='Status')),
                ('note', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_settlements', to='accounts.accountantprofile', verbose_name='Accountant')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='accounts.agentprofile', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Collection Settlement',
                'verbose_name_plural': 'Collection Settlements',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.collectionsettlement', verbose_name='Settlement Session'),
        ),
    ]
