# Generated by Django 6.0.5 on 2026-05-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('truck', 'شاحنة'), ('payment', 'مالي'), ('complaint', 'شكوى'), ('recycle', 'تدوير'), ('system', 'نظام')], default='system', max_length=15, verbose_name='النوع')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(blank=True, verbose_name='المحتوى')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
