# Generated by Django 6.0.5 on 2026-05-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('late', 'تأخر الجمع'), ('damaged', 'سلة تالفة'), ('missing', 'لم يتم الجمع'), ('other', 'أخرى')], max_length=20, verbose_name='النوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل')], default='new', max_length=15, verbose_name='الحالة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/', verbose_name='صورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='subscribers.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'شكوى',
                'verbose_name_plural': 'الشكاوى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('full', 'سلة ممتلئة'), ('damaged', 'سلة تالفة'), ('missing', 'سلة مفقودة'), ('empty', 'سلة فارغة')], max_length=20, verbose_name='نوع المشكلة')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='field_reports/', verbose_name='صورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to=settings.AUTH_USER_MODEL, verbose_name='السائق')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='subscribers.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'بلاغ ميداني',
                'verbose_name_plural': 'البلاغات الميدانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('rating', models.IntegerField(verbose_name='التقييم (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='تعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='subscribers.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'unique_together': {('subscriber', 'month')},
            },
        ),
    ]
