# Generated by Django 6.0.5 on 2026-06-05 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('subscribers', '0003_remove_subscriber_pause_reason_subscriber_route_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='fieldreport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Field Report', 'verbose_name_plural': 'Field Reports'},
        ),
        migrations.AlterModelOptions(
            name='servicerating',
            options={'verbose_name': 'Service Rating', 'verbose_name_plural': 'Service Ratings'},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='subscribers.subscriber', verbose_name='Subscriber'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='type',
            field=models.CharField(choices=[('late', 'Late Collection'), ('damaged', 'Damaged Bin'), ('missing', 'Missing Collection'), ('other', 'Other')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to=settings.AUTH_USER_MODEL, verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='field_reports/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='issue_type',
            field=models.CharField(choices=[('full', 'Full Bin'), ('damaged', 'Damaged Bin'), ('missing', 'Missing Bin'), ('empty', 'Empty Bin')], max_length=20, verbose_name='Issue Type'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='fieldreport',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='subscribers.subscriber', verbose_name='Subscriber'),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='month',
            field=models.DateField(verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='rating',
            field=models.IntegerField(verbose_name='Rating (1-5)'),
        ),
        migrations.AlterField(
            model_name='servicerating',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='subscribers.subscriber', verbose_name='Subscriber'),
        ),
    ]
