# Generated by Django 6.0.5 on 2026-06-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agentprofile_options_and_more'),
        ('complaints', '0002_alter_complaint_options_alter_fieldreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreport',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='accounts.driverprofile', verbose_name='Driver'),
        ),
    ]
