# Generated by Django 6.0.5 on 2026-05-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأخير')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='الهاتف')),
                ('license_number', models.CharField(blank=True, max_length=30, verbose_name='رقم رخصة القيادة')),
                ('truck_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الشاحنة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقين',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('admin', 'المدير العام'), ('accountant', 'المحاسب'), ('driver', 'السائق'), ('agent', 'المندوب'), ('subscriber', 'المشترك')], default='subscriber', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_staff', models.BooleanField(default=False, verbose_name='طاقم العمل')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأخير')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='الهاتف')),
                ('custody_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ العُهدة')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعّال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'مندوب',
                'verbose_name_plural': 'المناديب',
            },
        ),
    ]
