# Generated by Django 6.0.5 on 2026-05-31 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('driver_license', 'Driver license'), ('contract', 'Contract'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(blank=True, null=True, upload_to='employee_documents/')),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'accountant', 'driver', 'agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
