# Generated by Django 6.0.5 on 2026-06-05 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agentprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='user',
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
            },
        ),
        migrations.CreateModel(
            name='AccountantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to='accounts.employeeprofile', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Accountant Profile',
                'verbose_name_plural': 'Accountant Profiles',
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='accounts.employeeprofile', verbose_name='Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='accounts.employeeprofile', verbose_name='Employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.employeeprofile'),
        ),
    ]
