# Generated by Django 6.0.5 on 2026-05-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='النقاط')),
                ('reason', models.CharField(max_length=200, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='subscribers.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'معاملة نقاط',
                'verbose_name_plural': 'معاملات النقاط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecycleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plastic', 'بلاستيك'), ('metal', 'معادن'), ('paper', 'ورق'), ('bread', 'خبز')], max_length=15, verbose_name='الفئة')),
                ('bags_count', models.IntegerField(default=1, verbose_name='عدد الأكياس')),
                ('status', models.CharField(choices=[('pending', 'بانتظار'), ('collected', 'تم الجمع'), ('cancelled', 'ملغي')], default='pending', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_recycles', to=settings.AUTH_USER_MODEL, verbose_name='تم التأكيد بواسطة')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_requests', to='subscribers.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'طلب تدوير',
                'verbose_name_plural': 'طلبات التدوير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='المكافأة')),
                ('month', models.DateField(verbose_name='الشهر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='subscribers.subscriber', verbose_name='الفائز')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
            },
        ),
    ]
