# Generated by Django 6.0.5 on 2026-05-31 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0001_initial'),
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointstransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Points transaction', 'verbose_name_plural': 'Points transactions'},
        ),
        migrations.AlterModelOptions(
            name='recyclerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recycle request', 'verbose_name_plural': 'Recycle requests'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reward', 'verbose_name_plural': 'Rewards'},
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='recycle_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transaction', to='recycling.recyclerequest'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='subscribers.subscriber'),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='bags_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='category',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('paper', 'Paper'), ('bread', 'Bread')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_recycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='recyclerequest',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycle_requests', to='subscribers.subscriber'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='subscribers.subscriber'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
