# Generated by Django 6.0.5 on 2026-06-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agentprofile_options_and_more'),
        ('recycling', '0002_alter_pointstransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclerequest',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_recycles', to='accounts.driverprofile'),
        ),
    ]
