# Generated by Django 6.0.5 on 2026-05-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المنطقة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'موقوف')], default='active', max_length=10, verbose_name='الحالة')),
                ('boundaries', models.JSONField(blank=True, default=list, verbose_name='حدود المنطقة (إحداثيات)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منطقة',
                'verbose_name_plural': 'المناطق',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_days', models.JSONField(default=list, verbose_name='أيام الجمع')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('frozen', 'مُجمّد')], default='active', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_as_driver', to=settings.AUTH_USER_MODEL, verbose_name='السائق')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='zones.zone', verbose_name='المنطقة')),
            ],
            options={
                'verbose_name': 'مسار',
                'verbose_name_plural': 'المسارات',
            },
        ),
    ]
