# Generated by Django 6.0.5 on 2026-06-05 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agentprofile_options_and_more'),
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AlterField(
            model_name='route',
            name='collection_days',
            field=models.JSONField(default=list, verbose_name='Collection Days'),
        ),
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='accounts.driverprofile', verbose_name='Driver'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen')], default='active', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='route',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='zones.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='boundaries',
            field=models.JSONField(blank=True, default=list, verbose_name='Boundaries (Coordinates)'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
