# Generated by Django 6.0.5 on 2026-06-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_alter_route_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='boundaries',
            field=models.JSONField(blank=True, default=list, verbose_name='Boundaries (Coordinates)'),
        ),
    ]
