# Generated by Django 6.0.5 on 2026-05-25 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='خط العرض')),
                ('longitude', models.FloatField(verbose_name='خط الطول')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='السائق')),
            ],
            options={
                'verbose_name': 'موقع شاحنة',
                'verbose_name_plural': 'مواقع الشاحنات',
                'ordering': ['-timestamp'],
            },
        ),
    ]
