# Generated by Django 6.0.5 on 2026-05-31 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_alter_subscriber_options_and_more'),
        ('tracking', '0001_initial'),
        ('zones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trucklocation',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Truck location', 'verbose_name_plural': 'Truck locations'},
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CollectionVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected'), ('skipped', 'Skipped'), ('issue', 'Issue')], default='pending', max_length=15)),
                ('note', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='collection_visits', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='zones.route')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_visits', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['visit_date', 'id'],
                'unique_together': {('route', 'subscriber', 'visit_date')},
            },
        ),
    ]
