# Generated by Django 6.0.5 on 2026-06-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agentprofile_options_and_more'),
        ('tracking', '0002_alter_trucklocation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionvisit',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_visits', to='accounts.driverprofile'),
        ),
        migrations.AlterField(
            model_name='trucklocation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.driverprofile'),
        ),
    ]
